// Generated by delombok at Wed Oct 14 12:32:37 EEST 2020
package victor.training.patterns.structural.adapter.unify;

public class AdaptersToUnifyInterface {
    @java.lang.SuppressWarnings("all")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(AdaptersToUnifyInterface.class);

    void emitInsurance(Person p) {
        if (p.getSsn() != null) {
            audit("Person by SSN " + p.getSsn());
        } else {
            audit("Person by Birth Certificate# " + p.getBirthCertificateNo());
        }
    }

    void emitInsurance(Vessel v) {
        audit("Vessel IMO " + v);
    }

    private void audit(String message) {
        log.debug("Storing audit \'{}\'", message);
    }
}

class Person {
    private Long ssn;
    private String birthCertificateNo;

    public String getBirthCertificateNo() {
        return birthCertificateNo;
    }

    public Long getSsn() {
        return ssn;
    }
}

class Vessel {
    private String imo;

    public String getImo() {
        return imo;
    }
}
