// Generated by delombok at Wed Oct 14 12:32:37 EEST 2020
package victor.training.patterns.structural.facade.facade;

import victor.training.patterns.structural.facade.Facade;

@Facade
public class StockFacade {
	public void checkStock() {
		// 3 lines of domain Logic
		// TODO same as in CustomerFacade but with other subject/body
	}

	@java.lang.SuppressWarnings("all")
	public StockFacade() {
	}
}
