// Generated by delombok at Wed Oct 14 12:32:37 EEST 2020
package victor.training.patterns.structural.facade.entity;

import java.util.Date;

public class Customer {
	private Long id;
	private String name;
	private String email;
	private Site site;
	private Date creationDate;

	@java.lang.SuppressWarnings("all")
	public Customer() {
	}

	@java.lang.SuppressWarnings("all")
	public Long getId() {
		return this.id;
	}

	@java.lang.SuppressWarnings("all")
	public String getName() {
		return this.name;
	}

	@java.lang.SuppressWarnings("all")
	public String getEmail() {
		return this.email;
	}

	@java.lang.SuppressWarnings("all")
	public Site getSite() {
		return this.site;
	}

	@java.lang.SuppressWarnings("all")
	public Date getCreationDate() {
		return this.creationDate;
	}

	@java.lang.SuppressWarnings("all")
	public Customer setId(final Long id) {
		this.id = id;
		return this;
	}

	@java.lang.SuppressWarnings("all")
	public Customer setName(final String name) {
		this.name = name;
		return this;
	}

	@java.lang.SuppressWarnings("all")
	public Customer setEmail(final String email) {
		this.email = email;
		return this;
	}

	@java.lang.SuppressWarnings("all")
	public Customer setSite(final Site site) {
		this.site = site;
		return this;
	}

	@java.lang.SuppressWarnings("all")
	public Customer setCreationDate(final Date creationDate) {
		this.creationDate = creationDate;
		return this;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Customer)) return false;
		final Customer other = (Customer) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$id = this.getId();
		final java.lang.Object other$id = other.getId();
		if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
		final java.lang.Object this$name = this.getName();
		final java.lang.Object other$name = other.getName();
		if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
		final java.lang.Object this$email = this.getEmail();
		final java.lang.Object other$email = other.getEmail();
		if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
		final java.lang.Object this$site = this.getSite();
		final java.lang.Object other$site = other.getSite();
		if (this$site == null ? other$site != null : !this$site.equals(other$site)) return false;
		final java.lang.Object this$creationDate = this.getCreationDate();
		final java.lang.Object other$creationDate = other.getCreationDate();
		if (this$creationDate == null ? other$creationDate != null : !this$creationDate.equals(other$creationDate)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof Customer;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $id = this.getId();
		result = result * PRIME + ($id == null ? 43 : $id.hashCode());
		final java.lang.Object $name = this.getName();
		result = result * PRIME + ($name == null ? 43 : $name.hashCode());
		final java.lang.Object $email = this.getEmail();
		result = result * PRIME + ($email == null ? 43 : $email.hashCode());
		final java.lang.Object $site = this.getSite();
		result = result * PRIME + ($site == null ? 43 : $site.hashCode());
		final java.lang.Object $creationDate = this.getCreationDate();
		result = result * PRIME + ($creationDate == null ? 43 : $creationDate.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "Customer(id=" + this.getId() + ", name=" + this.getName() + ", email=" + this.getEmail() + ", site=" + this.getSite() + ", creationDate=" + this.getCreationDate() + ")";
	}
}
