// Generated by delombok at Wed Oct 14 12:32:37 EEST 2020
package victor.training.patterns.structural.facade.entity;

public class Email {
	private String to;
	private String from;
	private String subject;
	private String body;

	@java.lang.SuppressWarnings("all")
	public Email() {
	}

	@java.lang.SuppressWarnings("all")
	public String getTo() {
		return this.to;
	}

	@java.lang.SuppressWarnings("all")
	public String getFrom() {
		return this.from;
	}

	@java.lang.SuppressWarnings("all")
	public String getSubject() {
		return this.subject;
	}

	@java.lang.SuppressWarnings("all")
	public String getBody() {
		return this.body;
	}

	@java.lang.SuppressWarnings("all")
	public Email setTo(final String to) {
		this.to = to;
		return this;
	}

	@java.lang.SuppressWarnings("all")
	public Email setFrom(final String from) {
		this.from = from;
		return this;
	}

	@java.lang.SuppressWarnings("all")
	public Email setSubject(final String subject) {
		this.subject = subject;
		return this;
	}

	@java.lang.SuppressWarnings("all")
	public Email setBody(final String body) {
		this.body = body;
		return this;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Email)) return false;
		final Email other = (Email) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$to = this.getTo();
		final java.lang.Object other$to = other.getTo();
		if (this$to == null ? other$to != null : !this$to.equals(other$to)) return false;
		final java.lang.Object this$from = this.getFrom();
		final java.lang.Object other$from = other.getFrom();
		if (this$from == null ? other$from != null : !this$from.equals(other$from)) return false;
		final java.lang.Object this$subject = this.getSubject();
		final java.lang.Object other$subject = other.getSubject();
		if (this$subject == null ? other$subject != null : !this$subject.equals(other$subject)) return false;
		final java.lang.Object this$body = this.getBody();
		final java.lang.Object other$body = other.getBody();
		if (this$body == null ? other$body != null : !this$body.equals(other$body)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof Email;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $to = this.getTo();
		result = result * PRIME + ($to == null ? 43 : $to.hashCode());
		final java.lang.Object $from = this.getFrom();
		result = result * PRIME + ($from == null ? 43 : $from.hashCode());
		final java.lang.Object $subject = this.getSubject();
		result = result * PRIME + ($subject == null ? 43 : $subject.hashCode());
		final java.lang.Object $body = this.getBody();
		result = result * PRIME + ($body == null ? 43 : $body.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "Email(to=" + this.getTo() + ", from=" + this.getFrom() + ", subject=" + this.getSubject() + ", body=" + this.getBody() + ")";
	}
}
