// Generated by delombok at Wed Oct 14 12:32:37 EEST 2020
package victor.training.patterns.behavioral.strategy;

import java.io.InputStream;
import java.util.Properties;

public interface ConfigProvider {
	Properties getProperties();
}

class ConfigFileProvider implements ConfigProvider {
	public Properties getProperties() {
		try {
			try (InputStream is = ConfigFileProvider.class.getResourceAsStream("/application.properties")) {
				Properties properties = new Properties();
				properties.load(is);
				return properties;
			}
		} catch (final java.lang.Throwable $ex) {
			throw lombok.Lombok.sneakyThrow($ex);
		}
	}
}

class ConfigDatabaseProvider implements ConfigProvider {
	public Properties getProperties() {
		// Real implem goes here
		Properties properties = new Properties();
		properties.setProperty("someProp", "from database");
		return properties;
	}
}
