// Generated by delombok at Wed Oct 14 12:32:37 EEST 2020
package victor.training.patterns.structural.adapter;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import victor.training.patterns.structural.adapter.domain.UserService;

@SpringBootApplication
public class AdapterSpringApp implements CommandLineRunner {
	@java.lang.SuppressWarnings("all")
	private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(AdapterSpringApp.class);

	public static void main(String[] args) {
		SpringApplication.run(AdapterSpringApp.class, args);
	}

	@Autowired
	private UserService userService;

	public void run(String... args) throws Exception {
		userService.importUserFromLdap("jdoe");
		log.debug("Found users: " + userService.searchUserInLdap("doe"));
	}
}
