// Generated by delombok at Wed Oct 14 12:32:37 EEST 2020
package victor.training.patterns.structural.adapter.domain;
// This would normally be placed in a 'domain model' package
// i'm sorry
public class User {
	private String username;
	private String fullName;
	private String workEmail;

	@java.lang.SuppressWarnings("all")
	public String getUsername() {
		return this.username;
	}

	@java.lang.SuppressWarnings("all")
	public String getFullName() {
		return this.fullName;
	}

	@java.lang.SuppressWarnings("all")
	public String getWorkEmail() {
		return this.workEmail;
	}

	@java.lang.SuppressWarnings("all")
	public User setUsername(final String username) {
		this.username = username;
		return this;
	}

	@java.lang.SuppressWarnings("all")
	public User setFullName(final String fullName) {
		this.fullName = fullName;
		return this;
	}

	@java.lang.SuppressWarnings("all")
	public User setWorkEmail(final String workEmail) {
		this.workEmail = workEmail;
		return this;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof User)) return false;
		final User other = (User) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$username = this.getUsername();
		final java.lang.Object other$username = other.getUsername();
		if (this$username == null ? other$username != null : !this$username.equals(other$username)) return false;
		final java.lang.Object this$fullName = this.getFullName();
		final java.lang.Object other$fullName = other.getFullName();
		if (this$fullName == null ? other$fullName != null : !this$fullName.equals(other$fullName)) return false;
		final java.lang.Object this$workEmail = this.getWorkEmail();
		final java.lang.Object other$workEmail = other.getWorkEmail();
		if (this$workEmail == null ? other$workEmail != null : !this$workEmail.equals(other$workEmail)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof User;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $username = this.getUsername();
		result = result * PRIME + ($username == null ? 43 : $username.hashCode());
		final java.lang.Object $fullName = this.getFullName();
		result = result * PRIME + ($fullName == null ? 43 : $fullName.hashCode());
		final java.lang.Object $workEmail = this.getWorkEmail();
		result = result * PRIME + ($workEmail == null ? 43 : $workEmail.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "User(username=" + this.getUsername() + ", fullName=" + this.getFullName() + ", workEmail=" + this.getWorkEmail() + ")";
	}

	@java.lang.SuppressWarnings("all")
	public User(final String username, final String fullName, final String workEmail) {
		this.username = username;
		this.fullName = fullName;
		this.workEmail = workEmail;
	}
}
