// Generated by delombok at Wed Oct 14 12:32:37 EEST 2020
package victor.training.patterns.structural.facade.controller;

import org.springframework.stereotype.Controller;
import victor.training.patterns.structural.facade.facade.CustomerFacade;
import victor.training.patterns.structural.facade.facade.dto.CustomerDto;
//faking it
@Controller
public class CustomerController {
    private final CustomerFacade customerFacade;

    // @GetMapping
    public CustomerDto getById(long customerId) {
        return customerFacade.findById(customerId);
    }

    // @PostMapping
    public void register(CustomerDto customerDto) {
        customerFacade.registerCustomer(customerDto);
    }

    @java.lang.SuppressWarnings("all")
    public CustomerController(final CustomerFacade customerFacade) {
        this.customerFacade = customerFacade;
    }
}
